services:
  server:
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules